[package]
name = "euler"
version = "0.1.0"
authors = ["Emily Alice Michael <emilyam@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "^2.33.3"
integer-sqrt = "0.1.5"
num-bigint = "0.3"
